language: rust
rust:
  - stable
  - beta
  - nightly
before_script:
  - rustup component add clippy-preview
script:
  - cargo clippy
  # if you want the build job to fail when encountering warnings, use
  # - cargo clippy -- -D warnings
  - cargo test
