
sudo: required
dist: trusty
language: rust
rust:
  - stable
  - beta
  - nightly
addons:
    apt:
        packages:
            - libssl-dev
matrix:
  allow_failures:
    - rust: nightly

before_cache: |
  if [[ "$TRAVIS_RUST_VERSION" == nightly ]]; then
    RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install cargo-tarpaulin
  fi
cache: cargo
before_script:
  - cargo install just
  - rustup component add rustfmt-preview
  - rustup component add clippy-preview
script:
  - just test
after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == nightly ]]; then
    cargo tarpaulin --out Xml
    bash <(curl -s https://codecov.io/bash)
  fi